/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FeedingsImport } from './routes/feedings'
import { Route as DiapersImport } from './routes/diapers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FeedingsRoute = FeedingsImport.update({
  id: '/feedings',
  path: '/feedings',
  getParentRoute: () => rootRoute,
} as any)

const DiapersRoute = DiapersImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/diapers': {
      id: '/diapers'
      path: '/diapers'
      fullPath: '/diapers'
      preLoaderRoute: typeof DiapersImport
      parentRoute: typeof rootRoute
    }
    '/feedings': {
      id: '/feedings'
      path: '/feedings'
      fullPath: '/feedings'
      preLoaderRoute: typeof FeedingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/feedings': typeof FeedingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/feedings': typeof FeedingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/feedings': typeof FeedingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diapers' | '/feedings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diapers' | '/feedings'
  id: '__root__' | '/' | '/diapers' | '/feedings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiapersRoute: typeof DiapersRoute
  FeedingsRoute: typeof FeedingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiapersRoute: DiapersRoute,
  FeedingsRoute: FeedingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/diapers",
        "/feedings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/diapers": {
      "filePath": "diapers.tsx"
    },
    "/feedings": {
      "filePath": "feedings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
